name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker Image
        run: docker build -t banmatt/mlse_tp1 .
      
      - name: Push Docker Image
        run: docker push banmatt/mlse_tp1

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: deploy on VM
        run: sshpass -p '${{ secrets.VM_PASSWORD }}' ssh ${{secrets.VM_HOST}} docker pull banmatt/mlse_tp1:latest && docker stop mlse_tp1 && docker rm mlse_tp1 && docker run -d --name mlse_tp1 -p 5876:5876 banmatt/mlse_tp1:latest